# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: onelineaday_development
  pool: 5

production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false
  pool: 5 
  
